- src/lib.rs
This PR fixes #5 issue
Despite the fact that we have `OsStr` it's safe to convert lossy to `str` and replace `&` char with `^&`, because `URL` allow [percent-encoded](http://www.ietf.org/rfc/rfc3986.txt) Unicode chars only. We won't loss anything.
> Escape GET parameters in Windows

- src/lib.rs
before this change, opening a path containing a space only opens an empty cmd prompt.
Only tested on Windows 10.
> fix for filenames with spaces on windows

- Cargo.toml
- src/lib.rs
The code is adapted from rustup. Using ShellExecute is more efficient
and allows much better error handling. It also avoids some bugs, which
is the reason rustup switched to using this method.
Fixes #16
> Use ShellExecute rather than cmd.exe on windows

- Cargo.toml
We can't update to the latest version due to this in the Fedora.
> chore: Include README/LICENSE into a release tarball

- src/lib.rs
This restores the previous behavior on windows, and sticks to the recommended way of opening files on windows.
> Revert usage of Command::new(explorer) to ShellExecuteW

- src/main.rs
It may be better to encode an unsuccessful exit status in the `Err` variant instead of within the `Ok` variant. `io::Result<ExitStatus>` can be changed to `io::Result<()>` with an `io::Error` being created from `ExitStatus`. Another option is to create a custom error type. Most code, including `main.rs`, only checks the `Err` variant, assuming `Ok` was successful.
I can work on this change in another pull request if desired. This would be a breaking change but I think would result in more idiomatic code.
> Handle unsuccessful exit status in main.rs.

- rustfmt.toml
Add empty `rustfmt.toml` file to enforce defaults with overrides configuration from parent directory, home directory, and global config directory.
> Add empty rustfmt.toml file to enforce defaults.

- src/lib.rs
- src/main.rs
Change result from `io::Result<ExitStatus>` to `io::Result<()>`. Commands that exit with a successful exit status result in `Ok`, otherwise an `Err` variant is created.
Error information is gathered from the stderr channel of the process using a single read operation. This prevents the child process from keeping the main process alive if stderr is kept open.
`wslview` always reports a 0 exit status, even if the path does not exist, which results in false positives. The stderr channel is written to but ignored in this implementation because of the successful exit status. Other programs write to stderr as part of normal operation. Firefox on Linux never seems to be able to load all the modules it wants to, so it writes to stderr but successfully opens. The only way to avoid these false …
> Encode unsuccessful exit status in Err.

- src/lib.rs
IllumOS is the open source version of Solaris
> add Illumos support

- Cargo.toml
- src/lib.rs
`windows-sys` exposes the Windows API from machine-generated code based on Windows metadata. The crate is maintained by Microsoft and has generally faster compile time than winapi.
> Switch to windows-sys

- src/windows.rs
Related to issue #53. This adds double quotes (`" "`) around the path to the opened file.
> On Windows, add double quotes to path.

- Cargo.toml
To avoid duplicate dependencies in downstream crates.
> Upgrade to windows-sys v0.42.0

- .github/workflows/cross-platform-testing.yml
- Cargo.toml
- src/windows.rs
Use std `Command` instead of `ShellExecuteW` from windows sys crate.
This change was already attempted in: https://github.com/Byron/open-rs/issues/25 and later reverted in: https://github.com/Byron/open-rs/pull/27 and it it seems that it didn't work due to incorrect usage of `explorer` instead of `cmd /c start`.
(see https://github.com/helix-editor/helix/pull/5820#issuecomment-1416796024 for detailed explanation).
Related: https://github.com/helix-editor/helix/pull/5820
---
> feat(windows): use std Command

- Cargo.toml
- changelog.md
- src/haiku.rs
- src/ios.rs
- src/lib.rs
- src/macos.rs
- src/unix.rs
- src/windows.rs
Takes parts of https://github.com/Byron/open-rs/pull/64 and pushes it to completion, with
some additional improvements to documentation on the way.
> tokio support

- src/windows.rs
Previously, passing a URL with multiple query parameters on Windows would result in improper escaping, causing unexpected behavior when using it with "cmd /c". This commit addresses this issue by properly escaping all query parameters in the URL. Now, URLs with multiple query parameters are handled correctly on Windows.
See also:
* https://doc.rust-lang.org/std/os/windows/process/trait.CommandExt.html#tymethod.raw_arg
* https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/cmd
* https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/start
Related #67
> Fix Windows URL encoding for multiple query params

- Cargo.toml
- src/unix.rs
This PR fixes a bug I've been experiencing on WSL.
I have [`gio`](https://en.wikipedia.org/wiki/GIO_(software)) installed in my WSL environment because it comes bundled with [`glib`](https://en.wikipedia.org/wiki/GLib). Because of this, `open-rs` attempts to use `gio` and fails:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Launcher \"gio\" \"open\" \"https://google.com\" failed with ExitStatus(unix_wait_status(512))" }', examples/website.rs:4:38
stack backtrace:
0: rust_begin_unwind
at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
1: core::panicking::panic_fmt
at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
2: core::result::unwrap_failed
at …
```
> Use `wslview` on WSL even when `gio` is installed

- README.md
I found readme document is not following the new major version. This PR fixes it.
> Fix version in readme document

- src/main.rs
- src/windows.rs
On Windows OS, my colleagues and I conducted tests and found that:
- `cmd /c app` command can't open apps which are not in the env variables.
- However, `cmd /c start app` can open all apps exist in registry path `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths`. This is why I added `start` to open::with() under the Windows branch. And I recommend adding the registry address that represents the available scope to the doc or README (on Mac and Linux it may be other files), so that developers can quickly determine appnames available.
- Commands like `cmd /c "C:\app.exe"` can also open the application, but `cmd /c start "C:\app.exe"` does not work. Finally I found that `start "" "C:\app.exe"` is effective which "" is said to open a new window, and `start "" app` also …
> Fix open::with() on Windows. (#80)

- src/redox.rs
Redox has moved the launcher from /ui/bin to /usr/bin. Just use the PATH to locate it, so any future changes in location don't break this crate.
> redox: use PATH to find launcher

- src/lib.rs
- src/windows.rs
closes #90
ref: https://github.com/tauri-apps/plugins-workspace/issues/1003
> feat: use `ShellExecuteW` for detached spawning on Windows

- .github/workflows/cross-platform-testing.yml
- Cargo.toml
- src/lib.rs
- src/windows.rs
The build should also build a binary, which needs to be linked.
> try to validate linkage on all platforms

- src/windows.rs
Finally was able to reproduce https://github.com/Byron/open-rs/pull/91#issuecomment-1974905927
through https://github.com/tauri-apps/plugins-workspace/issues/1046
This was a mistake on my part in #91, I didn't notice that I used the wrong ABI, funnily enough I can still build on x86 & x64 targets using the wrong ABI.
> fix(windows): link using "system" ABI

- src/windows.rs
ref: https://github.com/tauri-apps/plugins-workspace/issues/1137
ref: https://github.com/tauri-apps/tauri/issues/9624
reference implementation in chromium: https://source.chromium.org/chromium/chromium/src/+/main:ui/base/win/shell.cc;l=83;drc=7e088bf159ef779ea494dd55bb48916be569b06a?q=OpenFileViaShell&ss=chromium%2Fchromium%2Fsrc
> fix(windows): use `ShellExecuteExW` to avoid freeze when opening directories

- src/lib.rs
This PR addresses the comments with `target_os` specifics.
Tested it with [Tier 3](https://github.com/rust-lang/rust/pull/121419) target.
> feat: Added visionOS support for Apple Vision Pro

- Cargo.toml
- src/lib.rs
This crate is essential to build typst on AIX. Add AIX support for it.
> Add AIX support

- src/windows.rs
Use `SHOpenFolderAndSelectItems` instead of `ShellExecuteExW` for folders on Windows
Fix #103
> fix(windows): use `SHOpenFolderAndSelectItems` for folders to respect expand to open folder setting fixes #103

- Cargo.toml
- src/windows.rs
closes #106
Strip UNC (`\?\\`) prefixes when opening directories using the `dunce` crate.
This PR also falls back to `ShellExecuteExW` in the rare case that `SHOpenFolderAndSelectItems` might fail, very unlikely but still good to do IMO.
However, I should note that `SHOpenFolderAndSelectItems` in some cases, instead of returning an error, it falls back to opening a default directory which is usually the `Documents` folder, this PR does not fix that as the Windows API doesn't return an error for it.
> fix(windows): fix `that_detached` for UNC path of a directory
